export const API_BASE_URL = process.env.NEXT_PUBLIC_API_BASE_URL ?? "";

export const API_ENDPOINTS = {
  login: "/login",
  register: "/merchant/registMember",
  forgetPassword: "/merchant/forgetPassword",
  registerSendCode: "/email/sendEmail",
  sendCheckEmail: "/email/sendCheckEmail",
  refreshToken: "/login",
  merchantInfo: "/merchant/info",
  merchantUpdate: "/merchant/update",
  walletList: "/merchantWallet/list",
  walletCollection: "/merchantWallet/collection",
  walletDecrypt: "/merchantWallet/decrypt",
  depositConfig: "/orderRecord/toDeposit",
  depositGetAddress: "/orderRecord/getAddress",
  depositResetAddress: "/orderRecord/resetAddress",
  withdrawConfig: "/orderRecord/toWithdraw",
  withdrawApply: "/orderRecord/withdraw",
  sendVerifyCode: "/email/sendCheckEmailWithoutEmail",
  merchantTransactions: "/merchantTransaction/page",
  transferConfig: "/merchantWallet/toTransfer",
  transferApply: "/merchantWallet/transfer",
  cardList: "/merchantCard/list",
  cardApplyBins: "/merchantCard/toApplyV2",
  cardPendingCount: "/merchantCard/pendingCount",
  cardApply: "/merchantCard/apply",
  kycSubmit: "/merchantKyc/submit",
  kycDetail: "/merchantKyc/detail",
  kycCountryList: "/country/list",
  kycPhoneList: "/merchantKyc/phone/list",
  kycOccupationList: "/merchantKyc/occupation/list",
  kycCityList: "/merchantKyc/city/list",
  cardHolderAdd: "/cardHolder/add",
  cardHolderEdit: "/cardHolder/edit",
  cardHolderDetail: "/cardHolder/detail",
  cardHolderBinCountries: "/cardUserInfo/getBinCountries",
  kycUploadFile: "/upload/kyc/file",
  cardDetail: "/merchantCard/importance",
  cardHide: "/merchantCard/hide",
  cardRecordPage: "/cardRecord/page",
  cardRechargeConfig: "/merchantCard/pre/deposit",
  cardRechargeApply: "/merchantCard/deposit",
  cardModify: "/merchantCard/modify",
  cardActiveCode: "/merchantCard/get/activeCode",
  cardActivate: "/merchantCard/activeCard",
  cardUpdatePin: "/merchantCard/update/pin",
  cardShipDetail: "/ship/detail",
  messageCenterPage: "/messageCenter/page",
  messageCenterRead: "/messageCenter/read",
  messageCenterAuth: "/messageCenter/auth",
  logout: "/merchant/logout",
  googleIsSecret: "/google/isGoogleSecret",
  googleQrCode: "/google/getQrcode",
  googleVerifySave: "/googleVerify/save",
  checkPasskey: "/login/check/passkey",


};
